plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
}

allprojects {
    group = 'com.tutorial.e-kart'
    version = '0.0.1-SNAPSHOT'
    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21

    test {
        useJUnitPlatform()
    }
}
